/*
 * m9sweeper dash
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.m9sweeper.trawler.framework.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * ClusterDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-09-28T11:46:20.946110-05:00[America/Chicago]")
public class ClusterDto {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("ipAddress")
  private String ipAddress = null;

  @SerializedName("port")
  private String port = null;

  @SerializedName("context")
  private String context = null;

  @SerializedName("groupId")
  private BigDecimal groupId = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("kubeConfig")
  private String kubeConfig = null;

  @SerializedName("isEnforcementEnabled")
  private Boolean isEnforcementEnabled = null;

  @SerializedName("isImageScanningEnforcementEnabled")
  private Boolean isImageScanningEnforcementEnabled = null;

  public ClusterDto id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public ClusterDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ClusterDto ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  @Schema(required = true, description = "")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public ClusterDto port(String port) {
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @Schema(required = true, description = "")
  public String getPort() {
    return port;
  }

  public void setPort(String port) {
    this.port = port;
  }

  public ClusterDto context(String context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @Schema(required = true, description = "")
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public ClusterDto groupId(BigDecimal groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  @Schema(required = true, description = "")
  public BigDecimal getGroupId() {
    return groupId;
  }

  public void setGroupId(BigDecimal groupId) {
    this.groupId = groupId;
  }

  public ClusterDto tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public ClusterDto addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @Schema(required = true, description = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public ClusterDto kubeConfig(String kubeConfig) {
    this.kubeConfig = kubeConfig;
    return this;
  }

   /**
   * Get kubeConfig
   * @return kubeConfig
  **/
  @Schema(required = true, description = "")
  public String getKubeConfig() {
    return kubeConfig;
  }

  public void setKubeConfig(String kubeConfig) {
    this.kubeConfig = kubeConfig;
  }

  public ClusterDto isEnforcementEnabled(Boolean isEnforcementEnabled) {
    this.isEnforcementEnabled = isEnforcementEnabled;
    return this;
  }

   /**
   * Get isEnforcementEnabled
   * @return isEnforcementEnabled
  **/
  @Schema(required = true, description = "")
  public Boolean isIsEnforcementEnabled() {
    return isEnforcementEnabled;
  }

  public void setIsEnforcementEnabled(Boolean isEnforcementEnabled) {
    this.isEnforcementEnabled = isEnforcementEnabled;
  }

  public ClusterDto isImageScanningEnforcementEnabled(Boolean isImageScanningEnforcementEnabled) {
    this.isImageScanningEnforcementEnabled = isImageScanningEnforcementEnabled;
    return this;
  }

   /**
   * Get isImageScanningEnforcementEnabled
   * @return isImageScanningEnforcementEnabled
  **/
  @Schema(required = true, description = "")
  public Boolean isIsImageScanningEnforcementEnabled() {
    return isImageScanningEnforcementEnabled;
  }

  public void setIsImageScanningEnforcementEnabled(Boolean isImageScanningEnforcementEnabled) {
    this.isImageScanningEnforcementEnabled = isImageScanningEnforcementEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterDto clusterDto = (ClusterDto) o;
    return Objects.equals(this.id, clusterDto.id) &&
        Objects.equals(this.name, clusterDto.name) &&
        Objects.equals(this.ipAddress, clusterDto.ipAddress) &&
        Objects.equals(this.port, clusterDto.port) &&
        Objects.equals(this.context, clusterDto.context) &&
        Objects.equals(this.groupId, clusterDto.groupId) &&
        Objects.equals(this.tags, clusterDto.tags) &&
        Objects.equals(this.kubeConfig, clusterDto.kubeConfig) &&
        Objects.equals(this.isEnforcementEnabled, clusterDto.isEnforcementEnabled) &&
        Objects.equals(this.isImageScanningEnforcementEnabled, clusterDto.isImageScanningEnforcementEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, ipAddress, port, context, groupId, tags, kubeConfig, isEnforcementEnabled, isImageScanningEnforcementEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    kubeConfig: ").append(toIndentedString(kubeConfig)).append("\n");
    sb.append("    isEnforcementEnabled: ").append(toIndentedString(isEnforcementEnabled)).append("\n");
    sb.append("    isImageScanningEnforcementEnabled: ").append(toIndentedString(isImageScanningEnforcementEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
