/*
 * m9sweeper dash
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.m9sweeper.trawler.framework.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.util.Objects;
/**
 * ImageDetailsDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-09-28T11:46:20.946110-05:00[America/Chicago]")
public class ImageDetailsDto {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("tag")
  private String tag = null;

  @SerializedName("dockerImageId")
  private String dockerImageId = null;

  @SerializedName("clusterId")
  private BigDecimal clusterId = null;

  @SerializedName("summary")
  private String summary = null;

  public ImageDetailsDto id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public ImageDetailsDto url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(required = true, description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ImageDetailsDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ImageDetailsDto tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @Schema(required = true, description = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public ImageDetailsDto dockerImageId(String dockerImageId) {
    this.dockerImageId = dockerImageId;
    return this;
  }

   /**
   * Get dockerImageId
   * @return dockerImageId
  **/
  @Schema(required = true, description = "")
  public String getDockerImageId() {
    return dockerImageId;
  }

  public void setDockerImageId(String dockerImageId) {
    this.dockerImageId = dockerImageId;
  }

  public ImageDetailsDto clusterId(BigDecimal clusterId) {
    this.clusterId = clusterId;
    return this;
  }

   /**
   * Get clusterId
   * @return clusterId
  **/
  @Schema(required = true, description = "")
  public BigDecimal getClusterId() {
    return clusterId;
  }

  public void setClusterId(BigDecimal clusterId) {
    this.clusterId = clusterId;
  }

  public ImageDetailsDto summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @Schema(required = true, description = "")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageDetailsDto imageDetailsDto = (ImageDetailsDto) o;
    return Objects.equals(this.id, imageDetailsDto.id) &&
        Objects.equals(this.url, imageDetailsDto.url) &&
        Objects.equals(this.name, imageDetailsDto.name) &&
        Objects.equals(this.tag, imageDetailsDto.tag) &&
        Objects.equals(this.dockerImageId, imageDetailsDto.dockerImageId) &&
        Objects.equals(this.clusterId, imageDetailsDto.clusterId) &&
        Objects.equals(this.summary, imageDetailsDto.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, name, tag, dockerImageId, clusterId, summary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageDetailsDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    dockerImageId: ").append(toIndentedString(dockerImageId)).append("\n");
    sb.append("    clusterId: ").append(toIndentedString(clusterId)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
