# D:efault values for elasticsearch-curator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronjob:
  enabled: true
  # At 01:00 every day
  schedule: "0 0 * * *"
  annotations: {}
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: "3"
  successfulJobsHistoryLimit: "1"

podSecurityPolicy:
  enabled: false

customArguments: []

pod:
  annotations: {}

#### URL of your kube-hunter api of app
dispatchUrl: ""


image:
  repository: aquasec/kube-hunter
  tag: 0.6.8
  pullPolicy: IfNotPresent

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

priorityClassName: ""

securityContext:
  enabled: true
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
