export enum Authority {
    SUPER_ADMIN = 'SUPER_ADMIN',
    ADMIN = 'ADMIN',
    READ_ONLY = 'READ_ONLY',
    KUBEHUNTER = 'KUBEHUNTER',
    KUBEBENCH = 'KUBEBENCH',
    TRAWLER ='TRAWLER',
    FALCO = 'FALCO'
}
