{{- if .Values.validatingWebhook.enabled }}
{{- if not (and .Values.ingress.hosts (index .Values.ingress.hosts 0))}}
{{- required "If the validating webhook is enabled, ingress.hosts must also have an entry. For clusters where traditional ingress can't be set up, see https://m9sweeper.io/docs/latest/docs/getting-started/advanced-install/#validating-webhook" "" }}
{{- end }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "m9sweeper-webhook"
webhooks:
  - name: "m9sweeper-validation-hook.m9sweeper.io"
    rules:
    - apiGroups: ["*"]
      apiVersions: ["v1", "v1beta1"]
      operations: ["CREATE"]
      resources: ["pods"]
      scope: "*"
    clientConfig:
      url: "https://{{ index .Values.ingress.hosts 0 }}/api/clusters/1/validation"
    admissionReviewVersions: ["v1", "v1beta1"]
    failurePolicy: Ignore
    sideEffects: None
    timeoutSeconds: 10

{{- end }}