export enum LicenseFeatures {
    IMAGE_SCANNING= 'IMAGE_SCANNING',
    IMAGE_SCANNING_ENFORCEMENT= 'IMAGE_SCANNING_ENFORCEMENT',
    IMAGE_SCANNING_EXCEPTIONS= 'IMAGE_SCANNING_EXCEPTIONS',
    LICENSE_KEY= 'LICENSE_KEY',
    INSTANCE_KEY= 'INSTANCE_KEY',
    EXPIRATION_DATE= 'EXPIRATION_DATE'
}