{
 "title": "m9sweeper dash",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "pod", "query": { "query": "label_values(pod)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Resource Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}) by (container)",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\"}\n)",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\"}\n)",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Memory Usage (WSS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (container)",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\"}\n)",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\"}\n)",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}) by (container)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}) by (container)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}) by (container)"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (container)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\", container != \"\", container != \"POD\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\", container != \"\", container != \"POD\"}) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Throttling (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[$__rate_interval])) by (container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[$__rate_interval])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compliance Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Compliance by Cluster (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "((sum by (cluster) (num_pods_compliant))/((sum by (cluster) (num_pods_compliant))+(sum by (cluster) (num_pods_noncompliant))))*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total CVEs by Cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      { "expr": "sum by (cluster) (total_cves)", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "$cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Compliance in $cluster",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 3, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (cluster) (num_pods_compliant{cluster=\"$cluster\"})",
       "legendFormat": "compliant pods"
      },
      {
       "expr": "sum by (cluster) (num_pods_noncompliant{cluster=\"$cluster\"})",
       "legendFormat": "noncompliant pods"
      }
     ]
    },
    {
     "title": "Images Running in $cluster",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "num_images_running{cluster=\"$cluster\"} - num_images_with_vulnerabilities{cluster=\"$cluster\"}",
       "legendFormat": "images without vulnerabilities"
      },
      {
       "expr": "num_images_with_vulnerabilities{cluster=\"$cluster\"}",
       "legendFormat": "images with vulnerabilities"
      }
     ]
    },
    {
     "title": "CVE Rate of Change in $cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rate(num_critical_cves{cluster=\"$cluster\"}[1m])",
       "legendFormat": "Critical CVEs"
      },
      {
       "expr": "rate(num_major_cves{cluster=\"$cluster\"}[1m])",
       "legendFormat": "Major CVEs"
      },
      {
       "expr": "rate(num_medium_cves{cluster=\"$cluster\"}[1m])",
       "legendFormat": "Medium CVEs"
      },
      {
       "expr": "rate(num_low_cves{cluster=\"$cluster\"}[1m])",
       "legendFormat": "Low CVEs"
      },
      {
       "expr": "rate(num_negligible_cves{cluster=\"$cluster\"}[1m])",
       "legendFormat": "Negligible CVEs"
      }
     ]
    },
    {
     "title": "Pod Compliance by Namespace in $cluster (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "((sum by (cluster, namespace) (num_pods_compliant{cluster=\"$cluster\"}))/((sum by (cluster, namespace) (num_pods_compliant{cluster=\"$cluster\"}))+(sum by (cluster, namespace) (num_pods_noncompliant{cluster=\"$cluster\"}))))*100",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}