apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trawler.fullname" . }}-secrets
  labels:
    {{- include "trawler.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_HOSTNAME: "{{ .Values.global.rabbitmq.host | default "m9sweeper-rabbitmq" | b64enc }}"
  RABBITMQ_PORT: "{{ .Values.global.rabbitmq.port | default "5672" | toString | b64enc }}"
  RABBITMQ_USERNAME: "{{ .Values.global.rabbitmq.username | default "guest" | b64enc }}"
  RABBITMQ_PASSWORD: "{{ .Values.global.rabbitmq.password | default "guest" | b64enc }}"
  RABBITMQ_QUEUE_NAME: "{{ .Values.global.rabbitmq.queueName | default "trawler_queue" | b64enc }}"
  M9SWEEPER_API_KEY: "{{ .Values.global.apiKey | b64enc }}"
