---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trawler-sa
  {{- if .Values.serviceAccount.annotations }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "trawler.labels" . | nindent 4 }}
{{- if .Values.image.credentials.create }}
imagePullSecrets:
- name: {{ .Chart.Name }}-registry-secret
{{- else if ne .Values.image.credentials.secretRef "" }}
imagePullSecrets:
- name: {{ .Values.image.credentials.secretRef }}
{{- end }}
