export default {
    email: process.env.DEFAULT_SUPER_ADMIN_EMAIL, // DEFAULTS TO NULL WHICH WILL LIKELY FAIL!
    password: process.env.DEFAULT_SUPER_ADMIN_PASSWORD // DEFAULTS TO NULL WHICH WILL LIKELY FAIL!
}
